# Generated by Django 4.0.4 on 2022-06-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quality',
            field=models.IntegerField(default=0),
        ),
    ]
