# Generated by Django 4.0.4 on 2022-06-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_book_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quality',
            new_name='quantity',
        ),
    ]
